version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: booking-postgres
    environment:
      POSTGRES_DB: resource_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - booking_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: booking-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/resource_booking
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DRIVER: org.postgresql.Driver
      JWT_SECRET: MzhmNGI3N2M5ZDJlNDFhNGI4ZjkyM2E3ZDYxYzhlMmY5YjA3ZDNlNGE1YzZmN2E4YjljMGQxZTJmM2E0YjVjNmQ3ZTg=
      SEED_ENABLED: "true"
      SEED_ADMIN_USERNAME: admin
      SEED_ADMIN_PASSWORD: Admin@123
      SEED_USER_USERNAME: john
      SEED_USER_PASSWORD: User@123
    ports:
      - "8080:8080"

volumes:
  booking_pg_data:
